version: "3.3"
services:
  app:
      container_name: app
      volumes:
        - .:/var/www/project:cached
      environment:
        - COMPOSER_MEMORY_LIMIT
        - SYMFONY_ENV
        - APP_ENV
        - SYMFONY_DEBUG
        - APP_DEBUG
      build:
          context: .
          dockerfile: docker/Dockerfile
          args:
            - PHP_IMAGE
            - DEMO_VERSION
      ports:
        - "8000:8000"
