version: "3.3"
services:
  app:
      build:
          context: .
          dockerfile: docker/Dockerfile
          args:
            - PHP_IMAGE
            - DEMO_VERSION
      ports:
        - "8000:8000"
