services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MNocon\GnuTerryPratchettBundle\Event\Subscriber\XClacksOverheadHeaderSubscriber:
    tags:
      - { name: kernel.event_subscriber }